package bgc.services.bps.financialbackgroundchecking.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-11-20T17:58:05.178+01:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "urn:v1.financialbackgroundchecking.bps.services.bgc", name = "FinancialBackgroundCheckingPortType")
@XmlSeeAlso({bgc.objects.vss.checkservice.v1.ObjectFactory.class, bgc.objects.vss.context.v4.ObjectFactory.class, bgc.objects.vss.functionalerror.v1.ObjectFactory.class, bgc.objects.bps.requestcheckcreditworthiness.v1.ObjectFactory.class, ObjectFactory.class, bgc.objects.bps.responsecheckcreditworthiness.v1.ObjectFactory.class, bgc.objects.vss.technicalerror.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FinancialBackgroundCheckingPortType {

    @WebMethod(operationName = "CheckService", action = "CheckService")
    @WebResult(name = "ResponseDataCheckService", targetNamespace = "urn:v1.financialbackgroundchecking.bps.services.bgc", partName = "CheckServiceResponseMessagePart")
    public bgc.objects.vss.checkservice.v1.ResponseDataCheckServiceType checkService(
        @WebParam(partName = "CheckServiceRequestMessagePart", name = "RequestDataCheckService", targetNamespace = "urn:v1.financialbackgroundchecking.bps.services.bgc")
        bgc.objects.vss.checkservice.v1.RequestDataCheckServiceType checkServiceRequestMessagePart
    ) throws FunctionalFaultMessage, TechnicalFaultMessage;

    @WebMethod(operationName = "CheckCreditworthiness", action = "CheckCreditworthiness")
    @WebResult(name = "ResponseDataCheckCreditworthiness", targetNamespace = "urn:v1.financialbackgroundchecking.bps.services.bgc", partName = "CheckCreditworthinessResponseMessagePart")
    public ResponseDataCheckCreditworthinessType checkCreditworthiness(
        @WebParam(partName = "CheckCreditworthinessRequestMessagePart", name = "RequestDataCheckCreditworthiness", targetNamespace = "urn:v1.financialbackgroundchecking.bps.services.bgc")
        RequestDataCheckCreditworthinessType checkCreditworthinessRequestMessagePart
    ) throws FunctionalFaultMessage, TechnicalFaultMessage;
}
