<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="../QueryCustomerCreditWorthinessCDBProvABCSImpl.wsdl"/>
      <rootElement name="ProcessCreditEligibilityVerificationEBM" namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/CustomerParty/V2"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/AIAMetaData/BEIM/BPS/SVC/FinancialBackgroundChecking/1.0/BPS-SVC-FinancialBackgroundChecking-1.0-standard-def.wsdl"/>
      <rootElement name="RequestDataCheckCreditworthiness" namespace="urn:v1.financialbackgroundchecking.bps.services.bgc"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [MON FEB 22 11:48:38 CET 2016]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns4="http://www.siebel.com/xml/BGCOrderStatusFeedbackRequestIO"
                xmlns:client="http://xmlns.oracle.com/QueryCustomerCreditWorthinessCDBProvABCSImpl"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns5="http://www.d-trix.com/namespace/qualify"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns7="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/Common/V2"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns6="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:wstns="urn:v1.financialbackgroundchecking.bps.services.bgc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns11="urn:v1.responsecheckcreditworthiness.bps.objects.bgc"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:funcerr="urn:v1.functionalerror.vss.objects.bgc"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns9="urn:oasis:names:tc:xacml:2.0:policy:schema:cd:04"
                xmlns:techerr="urn:v1.technicalerror.vss.objects.bgc"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ns0="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/EBO/CustomerParty/V2"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns2="http://schemas.oracle.com/bpel/extension"
                xmlns:ns3="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2"
                xmlns:ns10="urn:v1.requestcheckcreditworthiness.bps.objects.bgc"
                xmlns:ns8="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04"
                xmlns:ns12="urn:v1.checkservice.vss.objects.bgc"
                xmlns:ns1="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/CustomerParty/V2"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl ns4 client ns5 plnk ns7 ns6 ns9 ns0 xsd ns2 ns3 ns8 ns1 wsdl wstns ns11 funcerr techerr ns10 ns12 aia bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <wstns:RequestDataCheckCreditworthiness>
      <wstns:transactionData>
        <wstns:userContext>
          <wstns:applicationName>
            <xsl:text disable-output-escaping="no">AIA</xsl:text>
          </wstns:applicationName>
          <wstns:correlationId>
          	<xsl:text disable-output-escaping="no">123</xsl:text>
           <!--  <xsl:value-of select="oraext:generate-guid()"/> -->
          </wstns:correlationId>
          <wstns:userId>
            <xsl:text disable-output-escaping="no">id973498</xsl:text>
          </wstns:userId>
          <wstns:languageISO2Code>
            <xsl:text disable-output-escaping="no">EN</xsl:text>
          </wstns:languageISO2Code>
        </wstns:userContext>
      </wstns:transactionData>
      <wstns:criteria>
        <xsl:if test='/ns1:ProcessCreditEligibilityVerificationEBM/ns1:DataArea/ns1:ProcessCreditEligibilityVerification/ns3:Identification/ns3:ID != ""'>
          <wstns:customerIdentifier>
            <ns10:id>
              <xsl:value-of select="/ns1:ProcessCreditEligibilityVerificationEBM/ns1:DataArea/ns1:ProcessCreditEligibilityVerification/ns3:Identification/ns3:ID"/>
            </ns10:id>
          </wstns:customerIdentifier>
        </xsl:if>
        <xsl:if test='/ns1:ProcessCreditEligibilityVerificationEBM/ns1:DataArea/ns1:ProcessCreditEligibilityVerification/ns3:Identification/ns3:ID = ""'>
          <wstns:person>
            <ns10:birthDate>
              <!--<xsl:value-of select="/ns1:ProcessCreditEligibilityVerificationEBM/ns1:DataArea/ns1:ProcessCreditEligibilityVerification/ns1:RequestDateTime"/>-->
              <xsl:value-of select='concat(normalize-space(substring-after(substring-after(/ns1:ProcessCreditEligibilityVerificationEBM/ns1:DataArea/ns1:ProcessCreditEligibilityVerification/ns1:RequestDateTime,"/"),"/")),
              "-",
              substring-before(/ns1:ProcessCreditEligibilityVerificationEBM/ns1:DataArea/ns1:ProcessCreditEligibilityVerification/ns1:RequestDateTime,"/"),
              "-",
              substring-before(substring-after(/ns1:ProcessCreditEligibilityVerificationEBM/ns1:DataArea/ns1:ProcessCreditEligibilityVerification/ns1:RequestDateTime,"/"),"/"),
              "T00:00:00Z")'/>
            </ns10:birthDate>
            <ns10:name>
              <ns10:firstName>
                <xsl:value-of select="/ns1:ProcessCreditEligibilityVerificationEBM/ns1:DataArea/ns1:ProcessCreditEligibilityVerification/ns3:Identification/ns3:ApplicationObjectKey/ns3:ContextID"/>
              </ns10:firstName>
              <ns10:lastName>
                <xsl:value-of select="/ns1:ProcessCreditEligibilityVerificationEBM/ns1:DataArea/ns1:ProcessCreditEligibilityVerification/ns3:Identification/ns3:ApplicationObjectKey/ns3:ID"/>
              </ns10:lastName>
            </ns10:name>
            <ns10:legalAddress>
              <ns10:urbanAddress>
                <ns10:houseNumberFirst>
                  <xsl:value-of select="/ns1:ProcessCreditEligibilityVerificationEBM/ns1:DataArea/ns1:ProcessCreditEligibilityVerification/ns3:CustomerPartyReference/ns3:CustomerPartyAccountContactAddressCommunication/ns3:AddressCommunication/ns3:Address/ns3:LineThree"/>
                </ns10:houseNumberFirst>
                <ns10:houseNumberFirstSuffix>
                  <xsl:value-of select="/ns1:ProcessCreditEligibilityVerificationEBM/ns1:DataArea/ns1:ProcessCreditEligibilityVerification/ns3:CustomerPartyReference/ns3:CustomerPartyAccountContactAddressCommunication/ns3:AddressCommunication/ns3:Address/ns3:LineFour"/>
                </ns10:houseNumberFirstSuffix>
                <ns10:city>
                  <ns10:name>
                    <ns10:defaultName>
                      <xsl:value-of select="/ns1:ProcessCreditEligibilityVerificationEBM/ns1:DataArea/ns1:ProcessCreditEligibilityVerification/ns3:CustomerPartyReference/ns3:CustomerPartyAccountContactAddressCommunication/ns3:AddressCommunication/ns3:Address/ns3:LineSix"/>
                    </ns10:defaultName>
                  </ns10:name>
                </ns10:city>
                <ns10:street>
                  <ns10:name>
                    <ns10:defaultName>
                      <xsl:value-of select="/ns1:ProcessCreditEligibilityVerificationEBM/ns1:DataArea/ns1:ProcessCreditEligibilityVerification/ns3:CustomerPartyReference/ns3:CustomerPartyAccountContactAddressCommunication/ns3:AddressCommunication/ns3:Address/ns3:LineFive"/>
                    </ns10:defaultName>
                  </ns10:name>
                </ns10:street>
                <ns10:ZIPCode>
                  <ns10:value>
                    <xsl:value-of select="/ns1:ProcessCreditEligibilityVerificationEBM/ns1:DataArea/ns1:ProcessCreditEligibilityVerification/ns3:CustomerPartyReference/ns3:CustomerPartyAccountContactAddressCommunication/ns3:AddressCommunication/ns3:Address/ns3:PostalCode"/>
                  </ns10:value>
                </ns10:ZIPCode>
              </ns10:urbanAddress>
            </ns10:legalAddress>
          </wstns:person>
        </xsl:if>
      </wstns:criteria>
    </wstns:RequestDataCheckCreditworthiness>
  </xsl:template>
</xsl:stylesheet>
