<?xml version = '1.0' encoding = 'UTF-8'?>
<?oracle-xsl-mapper <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/EnterpriseBusinessServiceLibrary/Core/EBO/CustomerParty/V2/CustomerPartyEBS.wsdl"/>
      <rootElement name="ProcessCreditEligibilityVerificationResponseEBM" namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/CustomerParty/V2"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="XSD">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/ApplicationObjectLibrary/Siebel/V1/schemas/BGC/CWC/SHEQueryCreditDetailsResABM.xsd"/>
      <rootElement name="SHEQueryCreditDetailsResABM" namespace="http://www.siebel.com/xml/SHEQueryCreditDetailsResABM"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 10.1.3.4.0(build 080718.0645) AT [FRI AUG 22 10:39:10 GMT 2014]. -->
?>
<xsl:stylesheet version="1.0" xmlns:ns5="http://xmlns.oracle.com/EnterpriseServices/CustomerParty/V2" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:customerpartyebo="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/CustomerParty/V2" xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions" xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions" xmlns:ns4="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/EBO/CustomerParty/V2" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:svcdoc="http://xmlns.oracle.com/Services/Documentation/V1" xmlns:ns3="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns0="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04" xmlns:xsdLocal="http://www.siebel.com/xml/SHEQueryCreditDetailsResABM" xmlns:ns1="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/Common/V2" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:orcl="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns2="urn:oasis:names:tc:xacml:2.0:policy:schema:cd:04" xmlns:corecustomerpartyebs="http://xmlns.oracle.com/EnterpriseServices/Core/CustomerParty/V2" xmlns:corecom="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2" exclude-result-prefixes="xsl ns5 customerpartyebo ns4 xsd svcdoc ns3 soap ns0 ns1 ns2 corecustomerpartyebs corecom xsdLocal bpws aia ehdr hwf xp20 xref ora ids orcl" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue">
  <xsl:template match="/">
    <xsdLocal:SHEQueryCreditDetailsResABM>
      <xsdLocal:Color>
        <xsl:value-of select="/customerpartyebo:ProcessCreditEligibilityVerificationResponseEBM/customerpartyebo:DataArea/customerpartyebo:ProcessCreditEligibilityVerificationResponse/corecom:Identification/corecom:Revision/corecom:Description"/>
      </xsdLocal:Color>
      <xsdLocal:Reason>
        <xsl:value-of select="/customerpartyebo:ProcessCreditEligibilityVerificationResponseEBM/customerpartyebo:DataArea/customerpartyebo:ProcessCreditEligibilityVerificationResponse/corecom:Identification/corecom:Revision/corecom:Reason"/>
      </xsdLocal:Reason>
      <xsdLocal:MsgNo>
        <xsl:value-of select="/customerpartyebo:ProcessCreditEligibilityVerificationResponseEBM/customerpartyebo:DataArea/customerpartyebo:ProcessCreditEligibilityVerificationResponse/corecom:Identification/corecom:Revision/corecom:Number"/>
      </xsdLocal:MsgNo>
      <xsdLocal:CreditTimestamp>
       <!--  <xsl:value-of select="xp20:format-dateTime(/customerpartyebo:ProcessCreditEligibilityVerificationResponseEBM/customerpartyebo:DataArea/customerpartyebo:ProcessCreditEligibilityVerificationResponse/corecom:Identification/corecom:Revision/corecom:EffectiveDate,'[M01]/[D01]/[Y0001] [H01]:[m01]:[s01]')"/> -->
      </xsdLocal:CreditTimestamp>
      <xsdLocal:EvaluationMsg>
        <xsl:value-of select="/customerpartyebo:ProcessCreditEligibilityVerificationResponseEBM/customerpartyebo:DataArea/customerpartyebo:ProcessCreditEligibilityVerificationResponse/corecom:Identification/corecom:Revision/corecom:Code"/>
      </xsdLocal:EvaluationMsg>
      <xsdLocal:WegenerId>
        <xsl:value-of select="/customerpartyebo:ProcessCreditEligibilityVerificationResponseEBM/customerpartyebo:DataArea/customerpartyebo:ProcessCreditEligibilityVerificationResponse/corecom:Identification/corecom:ApplicationObjectKey/corecom:ContextID"/>
      </xsdLocal:WegenerId>
      <xsdLocal:Source>
        <xsl:value-of select="/customerpartyebo:ProcessCreditEligibilityVerificationResponseEBM/customerpartyebo:DataArea/customerpartyebo:ProcessCreditEligibilityVerificationResponse/corecom:Identification/corecom:AlternateObjectKey/corecom:ID"/>
      </xsdLocal:Source>
    </xsdLocal:SHEQueryCreditDetailsResABM>
  </xsl:template>
</xsl:stylesheet>
