<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="oramds:/apps/AIAMetaData/BEIM/BPS/SVC/FinancialBackgroundChecking/1.0/BPS-SVC-FinancialBackgroundChecking-1.0-standard-def.wsdl"/>
      <rootElement name="ResponseDataCheckCreditworthiness" namespace="urn:v1.financialbackgroundchecking.bps.services.bgc"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="../QueryCustomerCreditWorthinessCDBProvABCSImpl.wsdl"/>
      <rootElement name="ProcessCreditEligibilityVerificationResponseEBM" namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/CustomerParty/V2"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [MON NOV 30 09:25:53 CET 2015]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns4="http://www.siebel.com/xml/BGCOrderStatusFeedbackRequestIO"
                xmlns:client="http://xmlns.oracle.com/QueryCustomerCreditWorthinessCDBProvABCSImpl"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns7="http://www.d-trix.com/namespace/qualify"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns10="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/Common/V2"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns9="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:wstns="urn:v1.financialbackgroundchecking.bps.services.bgc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:ns1="urn:v1.responsecheckcreditworthiness.bps.objects.bgc"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:funcerr="urn:v1.functionalerror.vss.objects.bgc"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns12="urn:oasis:names:tc:xacml:2.0:policy:schema:cd:04"
                xmlns:techerr="urn:v1.technicalerror.vss.objects.bgc"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:ns8="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/EBO/CustomerParty/V2"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns6="http://schemas.oracle.com/bpel/extension"
                xmlns:ns5="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2"
                xmlns:ns0="urn:v1.requestcheckcreditworthiness.bps.objects.bgc"
                xmlns:ns11="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04"
                xmlns:ns2="urn:v1.checkservice.vss.objects.bgc"
                xmlns:ns3="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/CustomerParty/V2"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl wsdl wstns ns1 funcerr techerr xsd ns0 ns2 ns4 client ns7 plnk ns10 ns9 ns12 ns8 ns6 ns5 ns11 ns3 bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
  <xsl:template match="/">
    <ns3:ProcessCreditEligibilityVerificationResponseEBM>
      <ns3:DataArea>
        <ns3:ProcessCreditEligibilityVerificationResponse>
          <ns5:Identification>
            <ns5:Revision>
              <ns5:Number>
                <xsl:value-of select="/wstns:ResponseDataCheckCreditworthiness/wstns:customerCreditProfile/ns1:evaluationMessageNumber"/>
              </ns5:Number>
              <ns5:Description>
                <xsl:value-of select="/wstns:ResponseDataCheckCreditworthiness/wstns:customerCreditProfile/ns1:evaluationColour/ns1:value"/>
              </ns5:Description>
              <ns5:Code>
                <xsl:value-of select="/wstns:ResponseDataCheckCreditworthiness/wstns:customerCreditProfile/ns1:evaluationMessage"/>
              </ns5:Code>
              <ns5:EffectiveDate>
                <xsl:value-of select="/wstns:ResponseDataCheckCreditworthiness/wstns:customerCreditProfile/ns1:timeStamp"/>
              </ns5:EffectiveDate>
              <ns5:Reason>
                <xsl:value-of select="/wstns:ResponseDataCheckCreditworthiness/wstns:customerCreditProfile/ns1:evaluationReason"/>
              </ns5:Reason>
            </ns5:Revision>
          </ns5:Identification>
        </ns3:ProcessCreditEligibilityVerificationResponse>
      </ns3:DataArea>
    </ns3:ProcessCreditEligibilityVerificationResponseEBM>
  </xsl:template>
</xsl:stylesheet>
