package bgc.services.aia.customerconsultation.v1;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-11-09T15:26:49.895+01:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "AIA-CustomerConsultation-1.0-Service", 
                  wsdlLocation = "/wsdl/CustomerConsultationAIA/AIA-SVC-CustomerConsultation-1.0-standard-http_binding.wsdl",
                  targetNamespace = "urn:v1.customerconsultation.aia.services.bgc") 
public class AIACustomerConsultation10Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:v1.customerconsultation.aia.services.bgc", "AIA-CustomerConsultation-1.0-Service");
    public final static QName AIACustomerConsultation10SOAPPort = new QName("urn:v1.customerconsultation.aia.services.bgc", "AIA-CustomerConsultation-1.0-SOAP-Port");
    static {
        URL url = AIACustomerConsultation10Service.class.getResource("/wsdl/CustomerConsultationAIA/AIA-SVC-CustomerConsultation-1.0-standard-http_binding.wsdl");
        if (url == null) {
            url = AIACustomerConsultation10Service.class.getClassLoader().getResource("/wsdl/CustomerConsultationAIA/AIA-SVC-CustomerConsultation-1.0-standard-http_binding.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(AIACustomerConsultation10Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/wsdl/CustomerConsultationAIA/AIA-SVC-CustomerConsultation-1.0-standard-http_binding.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public AIACustomerConsultation10Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AIACustomerConsultation10Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AIACustomerConsultation10Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AIACustomerConsultation10Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AIACustomerConsultation10Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AIACustomerConsultation10Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CustomerConsultationPortType
     */
    @WebEndpoint(name = "AIA-CustomerConsultation-1.0-SOAP-Port")
    public CustomerConsultationPortType getAIACustomerConsultation10SOAPPort() {
        return super.getPort(AIACustomerConsultation10SOAPPort, CustomerConsultationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerConsultationPortType
     */
    @WebEndpoint(name = "AIA-CustomerConsultation-1.0-SOAP-Port")
    public CustomerConsultationPortType getAIACustomerConsultation10SOAPPort(WebServiceFeature... features) {
        return super.getPort(AIACustomerConsultation10SOAPPort, CustomerConsultationPortType.class, features);
    }

}
