package com.oracle.xmlns.getcustomercreditworthinessshereqabcsimpl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-11-20T15:35:32.700+01:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "client", 
                  wsdlLocation = "/wsdl/CheckCreditworthinessAIA/AIA.wsdl",
                  targetNamespace = "http://xmlns.oracle.com/GetCustomerCreditWorthinessSHEReqABCSImpl") 
public class Client extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.oracle.com/GetCustomerCreditWorthinessSHEReqABCSImpl", "client");
    public final static QName GetCustomerCreditWorthinessSHEReqABCSImplPt = new QName("http://xmlns.oracle.com/GetCustomerCreditWorthinessSHEReqABCSImpl", "GetCustomerCreditWorthinessSHEReqABCSImpl_pt");
    static {
        URL url = Client.class.getResource("/wsdl/CheckCreditworthinessAIA/AIA.wsdl");
        if (url == null) {
            url = Client.class.getClassLoader().getResource("/wsdl/CheckCreditworthinessAIA/AIA.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(Client.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/wsdl/CheckCreditworthinessAIA/AIA.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public Client(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Client(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Client() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Client(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Client(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Client(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns GetCustomerCreditWorthinessSHEReqABCSImpl
     */
    @WebEndpoint(name = "GetCustomerCreditWorthinessSHEReqABCSImpl_pt")
    public GetCustomerCreditWorthinessSHEReqABCSImpl getGetCustomerCreditWorthinessSHEReqABCSImplPt() {
        return super.getPort(GetCustomerCreditWorthinessSHEReqABCSImplPt, GetCustomerCreditWorthinessSHEReqABCSImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetCustomerCreditWorthinessSHEReqABCSImpl
     */
    @WebEndpoint(name = "GetCustomerCreditWorthinessSHEReqABCSImpl_pt")
    public GetCustomerCreditWorthinessSHEReqABCSImpl getGetCustomerCreditWorthinessSHEReqABCSImplPt(WebServiceFeature... features) {
        return super.getPort(GetCustomerCreditWorthinessSHEReqABCSImplPt, GetCustomerCreditWorthinessSHEReqABCSImpl.class, features);
    }

}
