<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="XSD">
      <schema location="ListOfBOTSLoggingIO.xsd"/>
      <rootElement name="ListOfBOTSLoggingIO" namespace="http://www.siebel.com/xml/BGCBOTSLogging"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/EnterpriseBusinessServiceLibrary/Industry/Communications/EBO/SalesOrder/V2/CommunicationsSalesOrderEBSV2.wsdl"/>
      <rootElement name="ProcessSalesOrderEBM" namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [THU AUG 17 12:53:27 CEST 2017]. -->
?>
<xsl:stylesheet version="1.0"
                xmlns:svcdoc="http://xmlns.oracle.com/Services/Documentation/V1"
                xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ns5="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/EBO/SalesOrder/V2"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:coresalesorderebs="http://xmlns.oracle.com/EnterpriseServices/Core/SalesOrder/V2"
                xmlns:ns0="http://xmlns.oracle.com/EnterpriseServices/SalesOrder/V2"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns6="urn:v2.commonprimary.beim.objects.bgc"
                xmlns:ns7="urn:v2.commonsecondary.beim.objects.bgc"
                xmlns:ns="http://schemas.xmlsoap.org/soap/encoding/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:ns4="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/Common/V2"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsdLocal="http://www.siebel.com/xml/BGCBOTSLogging"
                xmlns:salesorderebo="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/SalesOrder/V2"
                xmlns:ns8="urn:v2.product.beim.objects.bgc"
                xmlns:ns1="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:ns3="urn:oasis:names:tc:xacml:2.0:policy:schema:cd:04"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:corecom="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2"
                xmlns:ns9="urn:v2.resource.beim.objects.bgc"
                xmlns:ns2="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                xmlns:ehdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.esb.server.headers.ESBHeaderFunctions"
                exclude-result-prefixes="xsi xsl xsdLocal xsd svcdoc ns5 coresalesorderebs ns0 ns6 ns7 ns soap ns4 salesorderebo ns8 ns1 ns3 corecom ns9 ns2 aia bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
<xsl:output method="xml" indent="yes" omit-xml-declaration="yes" />
  <xsl:template match="/">
    <salesorderebo:ProcessSalesOrderEBM>
      <corecom:EBMHeader>
        <corecom:EBMID>
          <!-- <xsl:value-of select="oraext:generate-guid()"/> -->
        </corecom:EBMID>
      </corecom:EBMHeader>
      <salesorderebo:DataArea>
        <salesorderebo:ProcessSalesOrder>
          <corecom:Identification>
            <corecom:BusinessComponentID>
              <xsl:value-of select="/xsdLocal:ListOfBOTSLoggingIO/xsdLocal:ListOfBOTSLogging/xsdLocal:BOTSLogging/xsdLocal:ApplicationName"/>
            </corecom:BusinessComponentID>
            <corecom:ID>
              <xsl:value-of select="/xsdLocal:ListOfBOTSLoggingIO/xsdLocal:ListOfBOTSLogging/xsdLocal:BOTSLogging/xsdLocal:OrderID"/>
            </corecom:ID>
            <corecom:ContextID>
              <xsl:value-of select="/xsdLocal:ListOfBOTSLoggingIO/xsdLocal:ListOfBOTSLogging/xsdLocal:BOTSLogging/xsdLocal:Status"/>
            </corecom:ContextID>
            <corecom:ApplicationObjectKey>
              <corecom:ID>
                <xsl:value-of select="/xsdLocal:ListOfBOTSLoggingIO/xsdLocal:ListOfBOTSLogging/xsdLocal:BOTSLogging/xsdLocal:DetailedStatus"/>
              </corecom:ID>
            </corecom:ApplicationObjectKey>
            <corecom:AlternateObjectKey>
              <corecom:ID>
                <xsl:value-of select="/xsdLocal:ListOfBOTSLoggingIO/xsdLocal:ListOfBOTSLogging/xsdLocal:BOTSLogging/xsdLocal:TokenID"/>
              </corecom:ID>
              <corecom:ContextID>
                <xsl:value-of select="/xsdLocal:ListOfBOTSLoggingIO/xsdLocal:ListOfBOTSLogging/xsdLocal:BOTSLogging/xsdLocal:CustomerID"/>
              </corecom:ContextID>
            </corecom:AlternateObjectKey>
          </corecom:Identification>
          <xsl:if test='/xsdLocal:ListOfBOTSLoggingIO/xsdLocal:ListOfBOTSLogging/xsdLocal:BOTSLogging/xsdLocal:TimeStamp != ""'>
            <salesorderebo:OrderDateTime>
              <xsl:value-of select="concat(substring-after(substring-after(substring-before(/xsdLocal:ListOfBOTSLoggingIO/xsdLocal:ListOfBOTSLogging/xsdLocal:BOTSLogging/xsdLocal:TimeStamp, ' '), '/'), '/'), '-', substring-before(/xsdLocal:ListOfBOTSLoggingIO/xsdLocal:ListOfBOTSLogging/xsdLocal:BOTSLogging/xsdLocal:TimeStamp, '/'), '-', substring-before(substring-after(/xsdLocal:ListOfBOTSLoggingIO/xsdLocal:ListOfBOTSLogging/xsdLocal:BOTSLogging/xsdLocal:TimeStamp, '/'), '/'))"/>
              <xsl:value-of select="'T'"/>
              <xsl:value-of select="substring-after(/xsdLocal:ListOfBOTSLoggingIO/xsdLocal:ListOfBOTSLogging/xsdLocal:BOTSLogging/xsdLocal:TimeStamp,' ')"/>
              <xsl:value-of select="'Z'"/>
            </salesorderebo:OrderDateTime>
          </xsl:if>
        </salesorderebo:ProcessSalesOrder>
      </salesorderebo:DataArea>
    </salesorderebo:ProcessSalesOrderEBM>
  </xsl:template>
</xsl:stylesheet>
