package com.siebel.customui;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-11-10T15:40:35.217+01:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://siebel.com/CustomUI", name = "BGC_spcMCH_spcCustomer_spcConsultation")
@XmlSeeAlso({ObjectFactory.class, com.siebel.xml.bgcsoapexception.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BGCSpcMCHSpcCustomerSpcConsultation {

    @WebMethod(operationName = "BGCCustomerConsultationgetCustomerMigrationStatus_2", action = "document/http://siebel.com/CustomUI:BGCCustomerConsultationgetCustomerMigrationStatus_2")
    @WebResult(name = "BGCCustomerConsultationgetCustomerMigrationStatus_2_Output", targetNamespace = "http://siebel.com/CustomUI", partName = "BGCCustomerConsultationgetCustomerMigrationStatus_2_Output")
    public BGCCustomerConsultationgetCustomerMigrationStatus2Output bgcCustomerConsultationgetCustomerMigrationStatus2(
        @WebParam(partName = "BGCCustomerConsultationgetCustomerMigrationStatus_2_Input", name = "BGCCustomerConsultationgetCustomerMigrationStatus_2_Input", targetNamespace = "http://siebel.com/CustomUI")
        BGCCustomerConsultationgetCustomerMigrationStatus2Input bgcCustomerConsultationgetCustomerMigrationStatus2Input
    );
}
