<?xml version="1.0" encoding="UTF-8" ?>
<?oracle-xsl-mapper
  <!-- SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY. -->
  <mapSources>
    <source type="WSDL">
      <schema location="oramds:/apps/AIAMetaData/BEIM/AIA/SVC/CustomerConsultation/1.0/AIA-SVC-CustomerConsultation-1.0-standard-def.wsdl"/>
      <rootElement name="RequestDataGetCustomerMigrationStatus" namespace="urn:v1.customerconsultation.aia.services.bgc"/>
    </source>
  </mapSources>
  <mapTargets>
    <target type="WSDL">
      <schema location="oramds:/apps/AIAMetaData/AIAComponents/EnterpriseBusinessServiceLibrary/Core/EBO/CustomerParty/V2/CustomerPartyEBS.wsdl"/>
      <rootElement name="QueryCustomerPartyEBM" namespace="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/CustomerParty/V2"/>
    </target>
  </mapTargets>
  <!-- GENERATED BY ORACLE XSL MAPPER 11.1.1.7.0(build 130301.0647.0008) AT [MON JUL 13 13:32:14 CEST 2015]. -->
?>
<xsl:stylesheet version="1.0"
	xmlns:svcdoc="http://xmlns.oracle.com/Services/Documentation/V1"
	xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
	xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
	xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
	xmlns:ns3="http://xmlns.oracle.com/EnterpriseServices/CustomerParty/V2"
	xmlns:ns0="urn:v1.requestgetcustomermigrationstatus.aia.objects.bgc"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:ns6="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/Common/V2"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension"
	xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
	xmlns:wstns="urn:v1.customerconsultation.aia.services.bgc"
	xmlns:corecustomerpartyebs="http://xmlns.oracle.com/EnterpriseServices/Core/CustomerParty/V2"
	xmlns:ns5="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:ns1="urn:v1.responsegetcustomermigrationstatus.aia.objects.bgc"
	xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
	xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
	xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
	xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:funcerr="urn:v1.functionalerror.vss.objects.bgc"
	xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
	xmlns:ns8="urn:oasis:names:tc:xacml:2.0:policy:schema:cd:04"
	xmlns:techerr="urn:v1.technicalerror.vss.objects.bgc"
	xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
	xmlns:ns4="http://xmlns.oracle.com/EnterpriseObjects/Core/Custom/EBO/CustomerParty/V2"
	xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:corecom="http://xmlns.oracle.com/EnterpriseObjects/Core/Common/V2"
	xmlns:ns2="urn:v1.checkservice.vss.objects.bgc" xmlns:ns7="urn:oasis:names:tc:xacml:2.0:context:schema:cd:04"
	xmlns:customerpartyebo="http://xmlns.oracle.com/EnterpriseObjects/Core/EBO/CustomerParty/V2"
	xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
	exclude-result-prefixes="xsi xsl ns0 wsdl wstns ns1 funcerr techerr xsd ns2 svcdoc ns3 soap ns6 corecustomerpartyebs ns5 ns8 ns4 corecom ns7 customerpartyebo xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap">
	<xsl:template match="/">
		<customerpartyebo:QueryCustomerPartyEBM>
			<corecom:EBMHeader>
				<corecom:EBMID>
					<!-- <xsl:value-of select="oraext:generate-guid()"/> -->
				</corecom:EBMID>
			</corecom:EBMHeader>
			<customerpartyebo:DataArea>
				<customerpartyebo:Query>
					<corecom:QueryCode>
						<xsl:value-of
							select="/wstns:RequestDataGetCustomerMigrationStatus/wstns:customerIdentifier/ns0:id" />
					</corecom:QueryCode>
				</customerpartyebo:Query>
			</customerpartyebo:DataArea>
		</customerpartyebo:QueryCustomerPartyEBM>
	</xsl:template>
</xsl:stylesheet>
